---
title: "Demand_prj_Sc"
author: "MHarb"
date: "20/10/2020"
output: powerpoint_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## R Markdown

This is an R Markdown presentation. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.

When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document.


## Slide with Plot

```{r pressure}
#Growth Rates calculation (postponed as for the mean time manual calculation using excel is sufficient)

# Irr_GR <- Gro# GrowthRates <- read.csv("Kaala_Data.csv")
# 
# head(GrowthRates)
# Bour_GR <- GrowthRates$Bour
# 
#  wthRates$Irr
# agri_GR <- GrowthRates$agri
# plantation_GR <- GrowthRates$plantation
# Total.Agri_GR <- GrowthRates$Total.Agri

# write.table(dfrm, file="Kaala_Data_GR00.csv", sep=",", row.names=FALSE, col.names=TRUE)
```

```{r}
#source 1: https://www.datanovia.com/en/lessons/transform-data-to-normal-distribution-in-r/

#Drawing the raw data
library(ggpubr)
library(moments)
library(ggplot2)
library(bestNormalize)


#Demo data ElKaala Province growth rates
GrowthRates <- read.csv("Kaala_Data_GR.csv")
 
head(GrowthRates)

# Distribution of Plantation growth rate variable
ggdensity(GrowthRates, x = "Plantation_GR", fill = "lightgray", title = "Plantation") +
  stat_overlay_normal_density(color = "red", linetype = "dashed")

# Distribution of crops growth rate variable
ggdensity(GrowthRates, x = "Crops_GR", fill = "lightgray", title = "crops") +
  stat_overlay_normal_density(color = "red", linetype = "dashed")

# # Distribution of Rainfed growth rate variable
# ggdensity(GrowthRates, x = "Rainfed_GR", fill = "lightgray", title = "Rainfed") +
#   stat_overlay_normal_density(color = "red", linetype = "dashed")
# 
# # Distribution of Irrigated growth rate variable
# ggdensity(GrowthRates, x = "Irrigated_GR", fill = "lightgray", title = "Irrigated") +
#   stat_overlay_normal_density(color = "red", linetype = "dashed")
# # Distribution of Total_Agri variable
# 
# ggdensity(GrowthRates, x = "Total_GR", fill = "lightgray", title = "Total_Agri") +
#   stat_overlay_normal_density(color = "red", linetype = "dashed")
# 


# Store the transformation objects
yj_Plantation <- yeojohnson(GrowthRates$Plantation_GR,standardize=FALSE)
yj_Crops <- yeojohnson(GrowthRates$Crops_GR,standardize=FALSE)
# yj_Rainfed <- yeojohnson(GrowthRates$Rainfed_GR,standardize=TRUE)
# yj_Irrigated <- yeojohnson(GrowthRates$Irrigated_GR,standardize=TRUE)
# yj_Total <- yeojohnson(GrowthRates$Total_GR,standardize=TRUE)

# # Perform transformation
yj_Plantation_vals <- predict(yj_Plantation)
yj_Crops_vals <- predict(yj_Crops)
# yj_Rainfed_vals <- predict(yj_Rainfed)
# yj_Irrigated_vals <- predict(yj_Irrigated)
# yj_Total_vals <- predict(yj_Total)
print("Before")
skewness(GrowthRates$Plantation_GR, na.rm = TRUE)
skewness(GrowthRates$Crops_GR, na.rm = TRUE)
# skewness(GrowthRates$Rainfed_GR, na.rm = TRUE)
# skewness(GrowthRates$Irrigated_GR, na.rm = TRUE)
# skewness(GrowthRates$Total_GR, na.rm = TRUE)

print("mean/sd");mean(GrowthRates$Total_GR);sd(GrowthRates$Total_GR)
print("After")  
skewness(yj_Plantation_vals, na.rm = TRUE)
skewness(yj_Crops_vals, na.rm = TRUE)
# skewness(yj_Rainfed_vals, na.rm = TRUE)
# skewness(yj_Irrigated_vals, na.rm = TRUE)
# skewness(yj_Total_vals, na.rm = TRUE)

print("mean_a/sd_a");mean(yj_Total_vals);sd(yj_Total_vals)

#storing in a file
dfrm <- data.frame(yj_Plantation_vals=yj_Plantation_vals,yj_Crops_vals=yj_Crops_vals)
write.table(dfrm , file="yj_ElKalaa_Trans.csv", sep=",", row.names=FALSE, col.names=TRUE)

#Shapes after the transformation
#Demo data ElKaala Province growth rates
GrowthRates <- read.csv("yj_ElKalaa_Trans.csv")
 

# Distribution of Plantation growth rate variable
ggdensity(GrowthRates, x = "yj_Plantation_vals", fill = "lightgray", title = "yj_Plantation_vals") +
  stat_overlay_normal_density(color = "red", linetype = "dashed")

# Distribution of crops growth rate variable
ggdensity(GrowthRates, x = "yj_Crops_vals", fill = "lightgray", title = "yj_Crops_vals") +
  stat_overlay_normal_density(color = "red", linetype = "dashed")
# 
# # Distribution of Rainfed growth rate variable
# ggdensity(GrowthRates, x = "yj_Rainfed_vals", fill = "lightgray", title = "yj_Rainfed_vals") +
#   stat_overlay_normal_density(color = "red", linetype = "dashed")
# 
# # Distribution of Irrigated growth rate variable
# ggdensity(GrowthRates, x = "yj_Irrigated_vals", fill = "lightgray", title = "yj_Irrigated_vals") +
#   stat_overlay_normal_density(color = "red", linetype = "dashed")
# # Distribution of Total_Agri variable
# 
# ggdensity(GrowthRates, x = "yj_Total_vals", fill = "lightgray", title = "yj_Total_vals") +
#   stat_overlay_normal_density(color = "red", linetype = "dashed")


```

```{r}
#The extrapolation code is working perfect
library(forecast)
h <- 32
x <- read.csv("yj_ElKalaa_Trans.csv")
marathon <- ts(x$yj_Plantation_vals, start = 2004, end = 2018)#yj_Plantation_vals,yj_Crops_vals
#marathon <- ts(x[,2:length(x)], start = 2004, end = 2018)
fit.lin <- tslm(marathon ~ trend)
fcasts.lin <- forecast(fit.lin, h = h)
#fit.exp <- tslm(marathon ~ trend, lambda = 0)

#fcasts.exp <- forecast(fit.exp, h = h)

t <- time(marathon)
t.break1 <- 2030
t.break2 <- 2040
tb1 <- ts(pmax(0, t - t.break1), start = 2004)
tb2 <- ts(pmax(0, t - t.break2), start = 2004)

fit.pw <- tslm(marathon ~ t + tb1 + tb2)
t.new <- t[length(t)] + seq(h)
tb1.new <- tb1[length(tb1)] + seq(h)
tb2.new <- tb2[length(tb2)] + seq(h)

newdata <- cbind(t=t.new, tb1=tb1.new, tb2=tb2.new) %>%
  as.data.frame()
fcasts.pw <- forecast(fit.pw, newdata = newdata)

fit.spline <- tslm(marathon ~ t + I(t^2) + I(t^3) +
  I(tb1^3) + I(tb2^3))
fcasts.spl <- forecast(fit.spline, newdata = newdata)



autoplot(marathon) +
  autolayer(fitted(fit.lin), series = "Linear") +
  #autolayer(fitted(fit.exp), series = "Exponential") +
  autolayer(fitted(fit.pw), series = "Piecewise") +
  autolayer(fitted(fit.spline), series = "Cubic Spline") +
  autolayer(fcasts.pw, series="Piecewise") +
  autolayer(fcasts.lin, series="Linear", PI=FALSE) +
  #autolayer(fcasts.exp, series="Exponential", PI=FALSE) +
  autolayer(fcasts.spl, series="Cubic Spline", PI=FALSE) +
  xlab("Year") + ylab("LC Growth rate") +
  ggtitle("Growth Demand") +
  guides(colour = guide_legend(title = " "))

 
#storing in a file
dfrm_fcasts <- data.frame(fcasts.pw=fcasts.pw,fcasts.lin=fcasts.lin,fcasts.spl=fcasts.spl)
write.table(dfrm_fcasts, file="yj_ElKalaa_Trans_fcasts.csv", sep=",", row.names=FALSE, col.names=TRUE)





```


```{r}
#source:https://stats.stackexchange.com/questions/43482/transformation-to-increase-kurtosis-and-skewness-of-normal-r-v
# the degree for the different grades of skewness is working perfectly
fs = function(x,epsilon,delta) dnorm(sinh(delta*asinh(x)-epsilon))*delta*cosh(delta*asinh(x)-epsilon)/sqrt(1+x^2)

GrowthRates <- read.csv("yj_ElKalaa_Trans_fcasts.csv")
min <- min(GrowthRates$fcasts.pw.Point.Forecast)
max <- max(GrowthRates$fcasts.pw.Point.Forecast)
min
max
#GR = seq(min,max,0.0001)
GR = seq(-5,5,0.0001)
#GR = seq(-5,5,0.0001)#GrowthRates$transformed#
#GR = GrowthRates$fcasts.pw.Point.Forecast
G00 <- plot(GR,fs(GR,0,1), type="l",     
    lty=1,              # Line type: 0=blank, 1=solid, 2=dashed, 3=dotted, 4=dotdash, 5=longdash, 6=twodash  
     ,col="black")
G01 <-points(vec,fs(vec,1,1),type="l",lty=2,col="green")
G02 <-points(vec,fs(vec,2,1),type="l",lty=2,col="blue")
G03 <-points(vec,fs(vec,3,1),type="l",lty=2,col="pink")
G04 <-points(vec,fs(vec,-1,1),type="l",lty=2,col="brown")
G05 <-points(vec,fs(vec,-2,1),type="l",lty=2,col="red")
G06 <-points(vec,fs(vec,-3,1),type="l",lty=2,col="grey")

#storing in a file
dfrm_Sk <- data.frame(fs(vec,1,1),fs(vec,2,1),fs(vec,3,1),fs(vec,0,1),fs(vec,-1,1),fs(vec,-2,1),fs(vec,-3,1))
write.table(dfrm_Sk, file="yj_ElKalaa_Sk.csv", sep=",", row.names=FALSE, col.names=TRUE)

#back to original values
x <- read.csv("yj_ElKalaa_Sk.csv")
# fs.vec..1..1.	fs.vec..2..1.	fs.vec..3..1.	fs.vec..0..1.	fs.vec...1..1.	fs.vec...2..1.	fs.vec...3..1.

yj_obj_0 <- yeojohnson(x$fs.vec..0..1.,standardize=TRUE)
yj_obj_1 <- yeojohnson(x$fs.vec..1..1.,standardize=TRUE)
yj_obj_2 <- yeojohnson(x$fs.vec..2..1.,standardize=TRUE)
yj_obj_3 <- yeojohnson(x$fs.vec..3..1.,standardize=TRUE)
yj_obj_4 <- yeojohnson(x$fs.vec...1..1.,standardize=TRUE)
yj_obj_5 <- yeojohnson(x$fs.vec...2..1.,standardize=TRUE)
yj_obj_6 <- yeojohnson(x$fs.vec...3..1.,standardize=TRUE)



orig_vals_0 <- predict(yj_obj_0, newdata = x$fs.vec..2..1., inverse = TRUE)
orig_vals_1 <- predict(yj_obj_1, newdata = x$fs.vec..2..1., inverse = TRUE)
orig_vals_2 <- predict(yj_obj_2, newdata = x$fs.vec..2..1., inverse = TRUE)
orig_vals_3 <- predict(yj_obj_3, newdata = x$fs.vec..2..1., inverse = TRUE)
orig_vals_4 <- predict(yj_obj_4, newdata = x$fs.vec..2..1., inverse = TRUE)
orig_vals_5 <- predict(yj_obj_5, newdata = x$fs.vec..2..1., inverse = TRUE)
orig_vals_6 <- predict(yj_obj_6, newdata = x$fs.vec..2..1., inverse = TRUE)

dfrm_originalvalues <- data.frame(orig_vals_0,orig_vals_1,orig_vals_2,orig_vals_3,orig_vals_4,orig_vals_5,orig_vals_6)
write.table(orig_vals, file="yj_ElKalaa_fcasts_origvals.csv", sep=",", row.names=FALSE, col.names=TRUE)
```


```{r}

#https://www.youtube.com/watch?v=Xfdg0xqFjts
#how does sample size affect the sampling distribution of means?
str(iris)
iter <- 10000
n <- 5
mean <- rep(NA, iter)

for (i in 1:iter){
  #d <- sample(which(iris$Petal.Length > 5 & iris$Petal.Length < 20), n)
   d <- sample(iris$Petal.Length, n)

  mean[i] <-  mean(d)
  
}
hist(mean)
abline(v=mean(iris$Petal.Length), lty=2, lwd=3, col="blue")
```
```{r}
# Create a sequence of numbers between -10 and 10 incrementing by 0.1.
x <- seq(-2, 2, by = 0.001)

# Choose the mean as 2.5 and standard deviation as 0.5.
y <- rnorm(x, mean = 0, sd = 1)#sample(which(iris$Petal.Length > 0 & iris$Petal.Length < 1000), n)#

# Give the chart file a name.
png(file = "dnorm.png")

# plot(x,y)

# Save the file.
dev.off()

hist(y)

iter <-384
n <- 5
mean <- rep(NA, iter)

for (i in 1:iter){
  d <- sample(y, n)
  mean[i] <-  mean(d)
  
}
hist(mean)
iter_2 <- 32
m <- 12
timesamples <- rep(NA,324)
for (j in 1:32){
  s <- sample(mean, m)
  timesamples[j] <-  mean(s)
  
}
hist(timesamples)
```




```{r}
GrowthRates <- read.csv("yj_ElKalaa_Trans_fcasts.csv")
min <- min(GrowthRates$fcasts.pw.Point.Forecast)
max <- max(GrowthRates$fcasts.pw.Point.Forecast)
print(min);print(max)
# dfrm_originalvalues <- data.frame(min_pw= min,max_pw=max)
# write.table(dfrm_originalvalues, file="min-max_DF.csv", sep=",", row.names=FALSE, col.names=TRUE)

#how does sample size affect the sampling distribution of means?

skwedvalues<- read.csv("yj_ElKalaa_Sk.csv")
iter <- 1000
n <- 3
mean <- rep(NA, iter)
set.seed(1) # reproducible
for (i in 1:iter){
  #d <- sample(which(skwedvalues$fs.vec..1..1. > min & skwedvalues$fs.vec..3..1. < max), n, replace = FALSE)
  d <- sample(skwedvalues$fs.vec..1..1., n, replace = FALSE)

  mean[i] <-  mean(d)
  
}
hist(mean)
abline(v=mean(d), lty=2, lwd=3, col="blue")
df_draws <- data.frame(mean)
write.table(df_draws, file="df_draws.csv", sep=",", row.names=FALSE, col.names=TRUE)
```
```{r}
library(ggpubr)
library(moments)
library(ggplot2)
library(bestNormalize)
GrowthRates <- read.csv("yj_ElKalaa_Trans_fcasts.csv")
min <- min(GrowthRates$fcasts.pw.Point.Forecast)
max <- max(GrowthRates$fcasts.pw.Point.Forecast)
print(min);print(max)
# dfrm_originalvalues <- data.frame(min_pw= min,max_pw=max)
# write.table(dfrm_originalvalues, file="min-max_DF.csv", sep=",", row.names=FALSE, col.names=TRUE)

#how does sample size affect the sampling distribution of means?
#source:https://stackoverflow.com/questions/63678177/r-sample-rows-following-conditions-at-random-within-a-range-of-values-fixed-w
skwedvalues<- read.csv("yj_ElKalaa_Sk.csv")
set.seed(1) # reproducible
# data <- sample(which(skwedvalues$fs.vec..1..1. > min & skwedvalues$fs.vec..1..1. < max), 32)
draws <- skwedvalues[sample(which(skwedvalues$fs.vec..1..1. > min & skwedvalues$fs.vec..1..1. < max), 32),]


head(draws)

# draws
df_draws <- data.frame(draws)
write.table(df_draws, file="df_draws.csv", sep=",", row.names=FALSE, col.names=TRUE)

#back to original values
x <- read.csv("df_draws.csv")
yj_obj <- yeojohnson(x$fs.vec..2..1.,standardize=TRUE)

orig_vals <- predict(yj_obj, newdata = x$fs.vec..2..1., inverse = TRUE)

dfrm_originalvalues <- data.frame(orig_vals)
write.table(dfrm_originalvalues, file="df_draws_origvals.csv", sep=",", row.names=FALSE, col.names=TRUE)
```

